{
 "title": "Fast Farmer",
 "description": "Farming dashboard for use with chia-exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_farm",
    "label": "Selected Farm",
    "query": {
     "query": "label_values(fast_farmer_farmer_uptime,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fullnode Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fast_farmer_blockchain_synced{job=\"$selected_farm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fullnode Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fast_farmer_blockchain_height{job=\"$selected_farm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Netspace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fast_farmer_blockchain_netspace{job=\"$selected_farm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Netspace Share",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A + $A2) / $B", "type": "math" }
   ]
  },
  {
   "title": "Partials / 5 Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "increase(fast_farmer_total_partials_found{job=\"$selected_farm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total plots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fast_farmer_plot_counts{job=\"$selected_farm\"})",
     "legendFormat": "Total plots  {{instance}}"
    }
   ]
  },
  {
   "title": "Block Wins (24 hr)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fast_farmer_total_proofs_found{job=\"$selected_farm\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Wins (week)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fast_farmer_total_proofs_found{job=\"$selected_farm\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Est. Time to win",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "18.75 / (($A + $B) / 1024 / 1024 / 1024 / $C)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Partials (30 min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fast_farmer_total_partials_found{job=\"$selected_farm\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partials (24 hr)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fast_farmer_total_partials_found{job=\"$selected_farm\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signage Points per 9.375 seconds (target)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max(rate(fast_farmer_signage_point_interval_count{job=\"$selected_farm\"}[5m])) * 9.375",
     "legendFormat": "Signage Points"
    }
   ]
  },
  {
   "title": "Harvester Latency",
   "type": "timeseries",
   "description": "Time to Process a Signage Point",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(fast_farmer_qualities_latency_sum{job=\"$selected_farm\"}[$__rate_interval])",
     "legendFormat": "Quality Lookup"
    },
    {
     "expr": "rate(fast_farmer_proof_latency_sum{job=\"$selected_farm\"}[$__rate_interval])",
     "legendFormat": "Proof Lookup"
    },
    { "expression": "$A +$B", "type": "math" }
   ]
  },
  {
   "title": "Total Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fast_farmer_plot_file_size{job=\"$selected_farm\"})",
     "legendFormat": "{{type}} {{instance}}"
    }
   ]
  },
  {
   "title": "Effective Space (TBe)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Effective Space (TiBe)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Eligible Plots (per signage point)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(fast_farmer_total_passed_filter{job=\"$selected_farm\"}[5m])) * 9.375",
     "legendFormat": "Filter Passes"
    },
    {}
   ]
  },
  {
   "title": "Est. Daily Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "xch" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A + $A2) / $B * 4608", "type": "math" }
   ]
  },
  {
   "title": "Est. Monthly Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "xch" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A + $A2) / $B * 4608 * 365 / 12",
     "type": "math"
    }
   ]
  },
  {
   "title": "More Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A + $D - $B) / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Lookup Times (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(fast_farmer_signage_point_processing_latency_bucket{job=\"$selected_farm\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Count All Plots",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fast_farmer_plot_counts{job=\"$selected_farm\"} > 0",
     "legendFormat": "{{instance}} - K{{k_size}}:C{{c_level}}"
    }
   ]
  },
  {
   "title": "Total Size All Plots",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fast_farmer_plot_file_size{job=\"$selected_farm\"} > 0",
     "legendFormat": "{{instance}} - K{{k_size}}:C{{c_level}}"
    }
   ]
  },
  {
   "title": "Compression Level Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(c_level) (fast_farmer_plot_file_size{job=\"$selected_farm\"})",
     "legendFormat": "{{c_level}}"
    }
   ]
  },
  {
   "title": "K Size Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(k_size) (fast_farmer_plot_file_size{job=\"$selected_farm\"})",
     "legendFormat": "{{k_size}}"
    }
   ]
  },
  {
   "title": "Total plots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "fast_farmer_plot_counts{job=\"$selected_farm\"}",
     "legendFormat": "{{instance}} - K{{k_size}}:C{{c_level}}"
    }
   ]
  },
  {
   "title": "chia_farmer_proofs_found",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "fast_farmer_total_proofs_found{job=\"$selected_farm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}