global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "chia-exporter"
    static_configs:
    - targets: ["192.168.0.25:9914"]
      labels:
        application: 'chia-blockchain'
        network: 'mainnet'
