---
- name: Install fio and run tests on target servers
  hosts: all
  become: yes  # Use sudo to become the root user

  tasks:
    - name: Get NVMe smart-log before fio test on localhost
      local_action: shell nvme smart-log /dev/nvme0n1 > /tmp/smart_before.log

    - name: Get NVMe ocp smart-add-log before fio test on localhost
      local_action: shell nvme ocp smart-add-log /dev/nvme0n1 > /tmp/ocp_before.log

    - name: Run fio test on /dev/vdb
      ansible.builtin.command:
        cmd: fio --name=test --filename=/dev/vdb --rw=randrw --rwmixread=70 --numjobs=1 --direct=1 --ioengine=io_uring --bs=4k --iodepth=256 --runtime=600 --write_bw_log=/tmp/bw_log --write_iops_log=/tmp/iops_log --output-format=json --log_avg_msec=1000 --bwavgtime=1000 --norandommap --random_generator=tausworthe64
      register: fio_test_result

    - name: Show fio test output
      ansible.builtin.debug:
        var: fio_test_result.stdout_lines

    - name: Fetch bandwidth log
      ansible.builtin.fetch:
        src: /tmp/bw_log_bw.1.log
        dest: "./logs/{{ inventory_hostname }}_bw_log.log"
        flat: yes

    - name: Fetch IOPS log
      ansible.builtin.fetch:
        src: /tmp/iops_log_iops.1.log
        dest: "./logs/{{ inventory_hostname }}_iops_log.log"
        flat: yes

    - name: Display fio test summary with total IOPS and Bandwidth
      ansible.builtin.debug:
        msg: |
          VM: {{ inventory_hostname }}
          Total IOPS: {{ (fio_test_result.stdout | from_json).jobs[0].read.iops + (fio_test_result.stdout | from_json).jobs[0].write.iops }}
          Total Bandwidth Bytes: {{ (fio_test_result.stdout | from_json).jobs[0].read.bw_bytes + (fio_test_result.stdout | from_json).jobs[0].write.bw_bytes }}
          Total Bandwidth MB/s: {{ ((fio_test_result.stdout | from_json).jobs[0].read.bw_bytes + (fio_test_result.stdout | from_json).jobs[0].write.bw_bytes) | float / 1024 / 1024 | round(2) }}

    - name: Display fio test summary in markdown format
      ansible.builtin.debug:
        msg: |
          | VM Name | Total IOPS | Total Bandwidth Bytes | Total Bandwidth MB/s |
          |---------|------------|-----------------------|----------------------|
          | {{ inventory_hostname }} | {{ (fio_test_result.stdout | from_json).jobs[0].read.iops + (fio_test_result.stdout | from_json).jobs[0].write.iops }} | {{ (fio_test_result.stdout | from_json).jobs[0].read.bw_bytes + (fio_test_result.stdout | from_json).jobs[0].write.bw_bytes }} | {{ ((fio_test_result.stdout | from_json).jobs[0].read.bw_bytes + (fio_test_result.stdout | from_json).jobs[0].write.bw_bytes) | float / 1024 / 1024 | round(2) }} |

    - name: Get NVMe smart-log after fio test on localhost
      local_action: shell nvme smart-log /dev/nvme0n1 > /tmp/smart_after.log

    - name: Get NVMe ocp smart-add-log after fio test on localhost
      local_action: shell nvme ocp smart-add-log /dev/nvme0n1 > /tmp/ocp_after.log