---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Add passwordless sudo rule (less secure)
      lineinfile:
        path: /etc/sudoers
        line: "{{ sudo_user }} ALL=(ALL) NOPASSWD: ALL"
        state: present
      vars:
        sudo_user: "jm"
