global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: "prometheus"

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]  # Using localhost since node-exporter is in host network mode
        labels:
          instance: "node-exporter"

  - job_name: "nvidia-dcgm"
    scrape_interval: 1s  # More frequent scraping for GPU metrics
    static_configs:
      - targets: ["dcgm-exporter:9400"]
        labels:
          instance: "dcgm-exporter"


